# Generated by Django 2.0.5 on 2018-05-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0002_auto_20180503_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
